### ISSUE TITLE
Files with same paths are too truncated

### ISSUE THREAD

**Issue by gjtorikian** [atom/fuzzy-finder#17]
> in CMD+t, when you have multiple files with the same name and the path is to long it end with '...', which is fine if the paths of the files are almost equal

**Comment by simurai** [comment]
Next to making the fuzzy finder wider, there could also be horizontal scrolling, but maybe not that great having to switch to mouse/trackpad.

Or the lines could wrap instead of truncate. This should work:

```less
.fuzzy-finder {
  &.select-list ol.list-group li .primary-line,
  &.select-list ol.list-group li .secondary-line {

    // let lines wrap
    text-overflow: initial;
    white-space: initial;
    overflow: initial;

    // reduce line-height
    line-height: 1.4em;
    padding-top: .2em;
    padding-bottom: .2em;

    // make sure wrapped lines get padding
    padding-left: 21px;
    &.icon:before {
      margin-left: -21px;
    }
  }
}
```

![screen shot 2015-04-15 at 9 18 40 pm](https://cloud.githubusercontent.com/assets/378023/7158449/2746a77a-e3b5-11e4-9366-097f2b52829e.png)

The question is, if the wrapping should be the new default, or an option in the settings, or leave it for `styles.less`.
